#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed May 19 19:35:41 EEST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test2_behav -key {Behavioral:sim_1:Functional:test2} -tclbatch test2.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim test2_behav -key {Behavioral:sim_1:Functional:test2} -tclbatch test2.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

