build:
	javac src/*.java

run-p1:
	java -classpath ./src Crypto

run-p2:
	java -classpath ./src Stocks

run-p3:
	java -classpath ./src Valley

run-p4:
	java -classpath ./src Ridge

run-p5:
	java -classpath ./src Trigigel

clean:
	rm -f src/*.class

.PHONY: clean