#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jun 03 13:19:43 EEST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_ceas1_behav -key {Behavioral:sim_1:Functional:test_ceas1} -tclbatch test_ceas1.tcl -protoinst "protoinst_files/ceas_figure.protoinst" -log simulate.log"
xsim test_ceas1_behav -key {Behavioral:sim_1:Functional:test_ceas1} -tclbatch test_ceas1.tcl -protoinst "protoinst_files/ceas_figure.protoinst" -log simulate.log

